# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  AWS_ACCESS_KEY_ID:  # id of input
    description: 'AWS_ACCESS_KEY_ID'
    required: true
    default: ''
  AWS_SECRET_ACCESS_KEY:  # id of input
    description: 'AWS_SECRET_ACCESS_KEY'
    required: true
    default: ''
  AWS_SESSION_TOKEN:  # id of input
    description: 'AWS_SESSION_TOKEN'
    required: true
    default: ''
  
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.AWS_ACCESS_KEY_ID }}
    - ${{ inputs.AWS_SECRET_ACCESS_KEY }}
    - ${{ inputs.AWS_SESSION_TOKEN }}